### ISSUE TITLE
laravel orm 模型casts 属性字段定义object 写入日志报错

### ISSUE THREAD

**Issue by 2512422541** [Chance-fyi/operation-log#5]
laravel 8.x 创建 Test Model  定义 attrs 字段定义成 AsArrayObject 

```
namespace App\Models;

class Test extends Model
{
    protected $fillable = [
        'name',
        'attrs'
    ];

    protected $casts = [
        'attrs' => AsArrayObject::class
    ];
}
```
使用Test模型写入数据 并查看操作日志记录
```
\App\Models\Test::create([ 
      'name' => 'testName',
      'attrs' => [ 'id' => 1,
            'val' => 'testVal'
       ]
 ]);

$logStr = \Chance\Log\facades\OperationLog::getLog();

var_dump($logStr);
```
执行结果
![image](https://github.com/Chance-fyi/operation-log/assets/26000687/5322dc3d-a6af-4030-a6ca-28aaa7f4a6d4)

找到问题所在 因为字段被定义成了object 在获取字段数据的时候 object 类型 attrs 被强转成（string）会抛错

![image](https://github.com/Chance-fyi/operation-log/assets/26000687/00c7e9a5-31fe-4ee5-adcd-6fdb8059ba4a)

需要兼容下 object 数据类型 也转化一下

**Comment by Chance-fyi** [comment]
我创建了 laravel 8.x 的新项目，没有复现这个问题。你的具体版本号是多少？

**Comment by 2512422541** [comment]
佬 版本是 laravel 8.83.27 但是跟小版本没有关系  主要是设置了表模型对应关系后，获取日志就会抛这个错 
![image](https://github.com/Chance-fyi/operation-log/assets/26000687/8f21b4c7-2c01-4525-9983-354251e75706)
